(lang dune 2.7)

(generate_opam_files true)

(package
 (name compilers)
 (depends
  (angstrom
   (= 0.15.0))
  (core
   (= v0.16.1))
  (incr_dom
    (= v0.16.0))
  (ocaml
   (= 5.0.0))
  (z3
   (= 4.11.2))))
